# Site settings
title: Sean Durfee
email: sean@durfee.me
description: > # this means to ignore newlines until "baseurl:"
  I'm a multi-disciplinary designer based in Vancouver, BC. I 
  specialize in web, UI, product design, identities, branding, and 
  photography. Say hi (pleez).
baseurl: "" # the subpath of your site, e.g. /blog
url: "durfee.me" # the base hostname & protocol for your site
twitter_username: durfeee
github_username:  durfee

# Build settings
markdown: kramdown

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /projects/:path/
  photos:
    output: true
  videos:
    output: true

# Gems
gems: [
  jekyll-coffeescript,
  jekyll-watch,
  jekyll-assets,
  autoprefixer-rails
  ]