---
title: Sean Durfee
timezone: UTC
assets:
  digest: true
collections:
  pages:
    title: Pages
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
  uploads:
    title: Uploads
    output: true
email: sean@durfee.me
description: > 
  Sean Durfee is a multi-disciplinary designer,
  front-end developer and project manager
  based out of Vancouver, British Columbia.
baseurl: 
url: durfee.me
twitter_username: durfeee
github_username: durfee
markdown: kramdown
gems:
- jekyll-assets
- jekyll-coffeescript
- jekyll-watch
- autoprefixer-rails